name: Market Analysis Pipeline

on:
  # Allows manual triggering from the Actions tab
  workflow_dispatch:
  # Runs automatically on a schedule (Daily at 04:00 UTC, as previously configured)
  schedule:
    - cron: '0 4 * * *'

# Permissions required for the action to commit back to the repository
permissions:
  contents: write

jobs:
  analyze-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Setup Environment ---
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all required Python packages (for analysis AND scraping/processing)
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        # CRITICAL: If your data processor uses Playwright, install the browsers
        if pip freeze | grep -q playwright; then
          echo "Playwright detected. Installing browsers..."
          playwright install
        else
          echo "Playwright not detected in requirements."
        fi

    # --- Data Acquisition (Scraping/Processing) ---
    - name: Run Data Acquisition and Populate Database
      run: |
        echo "Running data acquisition..."
        
        # CRITICAL: This runs the verified script to generate market_reports.db
        python process_mombasa_data.py
        
        echo "Data acquisition finished."
        
        # Verify that the database was created
        if [ ! -f market_reports.db ]; then
          echo "ERROR: market_reports.db was not generated by process_mombasa_data.py. Analysis cannot proceed."
          # Exit with an error status if the DB is missing
          exit 1
        fi

    # --- Data Analysis ---
    - name: Run Mombasa Analysis
      # This generates report_data/mombasa_index.json and individual reports
      run: python analyze_mombasa.py

    # As you add more analyzers, list them here:
    # - name: Run Colombo Analysis
    #   run: python analyze_colombo.py

    # --- Library Consolidation ---
    - name: Build Consolidated Market Library
      # This reads the intermediate indexes and generates market-reports-library.json
      run: python build_library.py

    # --- Commit and Push Changes ---
    - name: Commit and push generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"

        # Add the generated data directory and the updated master library
        git add report_data/ || true
        git add market-reports-library.json || true

        # Commit only if there are changes
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit. Data might be unchanged or generation failed."
        else
          # [skip ci] prevents this commit from triggering another workflow run unnecessarily
          git commit -m "Automated Update: Regenerated analysis data and library index [skip ci]"
          git push
        fi